language: scala

notifications:
  email: false

jdk:
  - oraclejdk8

scala:
  - 2.11.8

cache:
  directories:
    - .sbt
    - $HOME/.ivy2
    - $HOME/.sbt/launchers/
    - $HOME/.cache/spark-versions

script:
  - sbt -sbt-version $SBT_VERSION
  - sbt test

env:
  - SBT_VERSION=0.13.13